-- This is what schema.sql will contain (example)
create table student (
    age integer not null check (age>=18),
    id bigint generated by default as identity,
    course varchar(255) not null,
    email varchar(255) not null unique,
    name varchar(255) not null,
    primary key (id)
);
create table student (age integer not null check (age>=18), id bigint generated by default as identity, course varchar(255) not null, email varchar(255) not null, name varchar(255) not null, primary key (id));
